// Mock PO Data for all events
const MockData = {
    // Generate mock POs for different statuses and events
    purchaseOrders: [
        // MODIFICATION EVENT POs (Open, Pending Approval, Cancelled)
        {
            poNumber: 'PO-2025-001',
            factory: 'Factory 1',
            warehouse: 'FCI',
            productName: 'Product A - Blue',
            createdDate: '2025-01-05',
            expectShipDate: '2025-02-15',
            eta: '2025-03-01',
            factoryAgent: 'Agent Smith',
            originPortName: 'Port 1',
            requestShipDate: '2025-02-15',
            poStatus: 'Open',
            oceanFreight: 2500,
            drayage: 800,
            chassis: 150,
            customDuties: 0,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: '',
            mbl: '',
            forwarder: '',
            carrier: '',
            costBasis: 'FOB',
            vessel: '',
            freightRate: '',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU001', description: 'Product A', variation: 'Blue', unitCost: 50, orderQty: 100, weight: 500, volume: 2.5, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-002',
            factory: 'Factory 2',
            warehouse: 'ARMS',
            productName: 'Widget B - Red',
            createdDate: '2025-01-10',
            expectShipDate: '2025-02-20',
            eta: '2025-03-05',
            factoryAgent: 'Agent Johnson',
            originPortName: 'Port 2',
            requestShipDate: '2025-02-20',
            poStatus: 'Pending Approval',
            oceanFreight: 3200,
            drayage: 950,
            chassis: 175,
            customDuties: 1200,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: 'Price update needed',
            destinationPort: 'LA/LB',
            hbl: '',
            mbl: '',
            forwarder: '',
            carrier: '',
            costBasis: 'CIF',
            vessel: '',
            freightRate: '',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU002', description: 'Product B', variation: 'Red', unitCost: 75, orderQty: 200, weight: 1000, volume: 5, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-003',
            factory: 'Factory 3',
            warehouse: 'FCI',
            productName: 'Component C - Green',
            createdDate: '2024-12-15',
            expectShipDate: '2025-01-20',
            eta: '2025-02-05',
            factoryAgent: 'Agent Williams',
            originPortName: 'Port 3',
            requestShipDate: '2025-01-20',
            poStatus: 'Cancelled',
            oceanFreight: 2800,
            drayage: 850,
            chassis: 160,
            customDuties: 0,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: 'Customer cancelled order',
            destinationPort: 'Louisville',
            hbl: '',
            mbl: '',
            forwarder: '',
            carrier: '',
            costBasis: 'DDP',
            vessel: '',
            freightRate: '',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU003', description: 'Product C', variation: 'Green', unitCost: 60, orderQty: 150, weight: 750, volume: 3.75, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },

        // PRODUCTION EVENT POs (Approved, Agent Approved, Agent Rejected, In Production, Ready at Factory, Container Booked, Space Released, Hold)
        {
            poNumber: 'PO-2025-004',
            factory: 'Factory 4',
            warehouse: 'FCI',
            createdDate: '2025-01-08',
            expectShipDate: '2025-03-01',
            eta: '2025-03-20',
            factoryAgent: 'Agent Brown',
            originPortName: 'Port 1',
            requestShipDate: '2025-03-01',
            poStatus: 'Approved',
            oceanFreight: 2700,
            drayage: 900,
            chassis: 165,
            customDuties: 0,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: '',
            mbl: '',
            forwarder: '',
            carrier: '',
            costBasis: 'FOB',
            vessel: '',
            freightRate: '2500',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU004', description: 'Product D', variation: 'Black', unitCost: 90, orderQty: 300, weight: 1500, volume: 7.5, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-005',
            factory: 'Factory 5',
            warehouse: 'ARMS',
            createdDate: '2025-01-12',
            expectShipDate: '2025-03-10',
            eta: '2025-03-28',
            factoryAgent: 'Agent Davis',
            originPortName: 'Port 2',
            requestShipDate: '2025-03-10',
            poStatus: 'Agent Approved',
            oceanFreight: 3100,
            drayage: 920,
            chassis: 170,
            customDuties: 950,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-02-05',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '',
            mbl: '',
            forwarder: 'FMED',
            carrier: 'Hapag-Lloyd',
            costBasis: 'CIF',
            vessel: '',
            freightRate: '3000',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU005', description: 'Product E', variation: 'White', unitCost: 85, orderQty: 250, weight: 1250, volume: 6.25, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-006',
            factory: 'Factory 6',
            warehouse: 'FCI',
            createdDate: '2025-01-15',
            expectShipDate: '2025-03-15',
            eta: '2025-04-02',
            factoryAgent: 'Agent Miller',
            originPortName: 'Port 3',
            requestShipDate: '2025-03-15',
            poStatus: 'Agent Rejected',
            oceanFreight: 2600,
            drayage: 880,
            chassis: 155,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Rejected',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: 'Material shortage - unable to fulfill order',
            destinationPort: 'Louisville',
            hbl: '',
            mbl: '',
            forwarder: '',
            carrier: '',
            costBasis: 'FOB',
            vessel: '',
            freightRate: '',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU006', description: 'Product F', variation: 'Yellow', unitCost: 70, orderQty: 180, weight: 900, volume: 4.5, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-007',
            factory: 'Factory 7',
            warehouse: 'ARMS',
            createdDate: '2024-12-20',
            expectShipDate: '2025-02-25',
            eta: '2025-03-15',
            factoryAgent: 'Agent Wilson',
            originPortName: 'Port 4',
            requestShipDate: '2025-02-25',
            poStatus: 'In production',
            oceanFreight: 3300,
            drayage: 960,
            chassis: 180,
            customDuties: 1100,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-01-15',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '',
            mbl: '',
            forwarder: 'HLS',
            carrier: 'SLS',
            costBasis: 'CIF',
            vessel: '',
            freightRate: '3200',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU007', description: 'Product G', variation: 'Orange', unitCost: 95, orderQty: 220, weight: 1100, volume: 5.5, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-008',
            factory: 'Factory 8',
            warehouse: 'FCI',
            createdDate: '2024-12-10',
            expectShipDate: '2025-02-10',
            eta: '2025-02-28',
            factoryAgent: 'Agent Moore',
            originPortName: 'Port 1',
            requestShipDate: '2025-02-10',
            poStatus: 'Ready at Factory',
            oceanFreight: 2850,
            drayage: 870,
            chassis: 160,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-01-05',
            readyDate: '2025-02-05',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: '',
            mbl: '',
            forwarder: 'DeWell',
            carrier: 'CMA CGM Securities B.V.',
            costBasis: 'FOB',
            vessel: '',
            freightRate: '2700',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU008', description: 'Product H', variation: 'Purple', unitCost: 80, orderQty: 190, weight: 950, volume: 4.75, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-009',
            factory: 'Factory 1',
            warehouse: 'ARMS',
            createdDate: '2024-12-05',
            expectShipDate: '2025-02-05',
            eta: '2025-02-23',
            factoryAgent: 'Agent Taylor',
            originPortName: 'Port 2',
            requestShipDate: '2025-02-05',
            poStatus: 'Container Booked',
            oceanFreight: 3450,
            drayage: 980,
            chassis: 185,
            customDuties: 1050,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-12-28',
            readyDate: '2025-01-30',
            containerBookedDate: '2025-02-01',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: 'CONT123456',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '',
            mbl: '',
            forwarder: 'Donglixin',
            carrier: 'ZIM',
            costBasis: 'CIF',
            vessel: '',
            freightRate: '3500',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU009', description: 'Product I', variation: 'Gray', unitCost: 88, orderQty: 210, weight: 1050, volume: 5.25, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-010',
            factory: 'Factory 2',
            warehouse: 'FCI',
            createdDate: '2024-11-28',
            expectShipDate: '2025-01-28',
            eta: '2025-02-15',
            factoryAgent: 'Agent Anderson',
            originPortName: 'Port 3',
            requestShipDate: '2025-01-28',
            poStatus: 'Shipped',
            oceanFreight: 2950,
            drayage: 890,
            chassis: 165,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-12-20',
            readyDate: '2025-01-22',
            containerBookedDate: '2025-01-24',
            spaceReleasedDate: '2025-01-26',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-01-28',
            containerNumber: 'CONT234567',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL234567',
            mbl: 'MBL234567',
            forwarder: 'Top Ocean',
            carrier: 'WHL',
            costBasis: 'FOB',
            vessel: 'Sea Voyager',
            freightRate: '2900',
            portDate: '',
            trackingUrl: 'http://tracking.example.com/CONT234567',
            telexRelease: 'Yes',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU010', description: 'Product J', variation: 'Brown', unitCost: 92, orderQty: 240, weight: 1200, volume: 6, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-011',
            factory: 'Factory 3',
            warehouse: 'ARMS',
            createdDate: '2025-01-18',
            expectShipDate: '2025-03-20',
            eta: '2025-04-08',
            factoryAgent: 'Agent Thomas',
            originPortName: 'Port 4',
            requestShipDate: '2025-03-20',
            poStatus: 'Hold',
            oceanFreight: 3200,
            drayage: 940,
            chassis: 175,
            customDuties: 980,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-02-15',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'Yes',
            holdReason: 'Quality inspection pending',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '',
            mbl: '',
            forwarder: 'PNB',
            carrier: 'MSC',
            costBasis: 'CIF',
            vessel: '',
            freightRate: '3100',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU011', description: 'Product K', variation: 'Pink', unitCost: 78, orderQty: 170, weight: 850, volume: 4.25, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },

        // LOGISTICS EVENT POs (Shipped, Arrived At Port, Picked Up, Arrived At WH, Empty Notification)
        {
            poNumber: 'PO-2024-050',
            factory: 'Factory 4',
            warehouse: 'FCI',
            createdDate: '2024-11-15',
            expectShipDate: '2025-01-15',
            eta: '2025-02-02',
            factoryAgent: 'Agent Jackson',
            originPortName: 'Port 1',
            requestShipDate: '2025-01-15',
            poStatus: 'Shipped',
            oceanFreight: 3350,
            drayage: 920,
            chassis: 170,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-12-10',
            readyDate: '2025-01-10',
            containerBookedDate: '2025-01-12',
            spaceReleasedDate: '2025-01-13',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-01-15',
            containerNumber: 'CONT345678',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL345678',
            mbl: 'MBL345678',
            forwarder: 'FMED',
            carrier: 'Hapag-Lloyd',
            costBasis: 'FOB',
            vessel: 'Pacific Express',
            freightRate: '3300',
            portDate: '',
            trackingUrl: 'http://tracking.example.com/CONT345678',
            telexRelease: 'Yes',
            customs: '',
            laceyAct: '',
            packingList: 'Yes',
            doField: '',
            vesselStatus: 'VESSEL',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU012', description: 'Product L', variation: 'Silver', unitCost: 105, orderQty: 280, weight: 1400, volume: 7, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2024-051',
            factory: 'Factory 5',
            warehouse: 'ARMS',
            createdDate: '2024-11-10',
            expectShipDate: '2025-01-10',
            eta: '2025-01-28',
            factoryAgent: 'Agent White',
            originPortName: 'Port 2',
            requestShipDate: '2025-01-10',
            poStatus: 'Arrived At Port',
            oceanFreight: 3650,
            drayage: 990,
            chassis: 180,
            customDuties: 1150,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-12-05',
            readyDate: '2025-01-05',
            containerBookedDate: '2025-01-07',
            spaceReleasedDate: '2025-01-08',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-01-10',
            containerNumber: 'CONT456789',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: 'HBL456789',
            mbl: 'MBL456789',
            forwarder: 'TOPOCEAN',
            carrier: 'Maersk',
            costBasis: 'CIF',
            vessel: 'Atlantic Star',
            freightRate: '3600',
            portDate: '2025-01-28',
            trackingUrl: 'http://tracking.example.com/CONT456789',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal A',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '2025-02-05',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU013', description: 'Product M', variation: 'Gold', unitCost: 110, orderQty: 260, weight: 1300, volume: 6.5, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2024-052',
            factory: 'Factory 6',
            warehouse: 'FCI',
            createdDate: '2024-11-05',
            expectShipDate: '2025-01-05',
            eta: '2025-01-23',
            factoryAgent: 'Agent Harris',
            originPortName: 'Port 3',
            requestShipDate: '2025-01-05',
            poStatus: 'Picked Up',
            oceanFreight: 3400,
            drayage: 910,
            chassis: 165,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-11-28',
            readyDate: '2024-12-30',
            containerBookedDate: '2025-01-02',
            spaceReleasedDate: '2025-01-03',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-01-05',
            containerNumber: 'CONT567890',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL567890',
            mbl: 'MBL567890',
            forwarder: 'HLS',
            carrier: 'SLS',
            costBasis: 'FOB',
            vessel: 'Global Trader',
            freightRate: '3400',
            portDate: '2025-01-23',
            trackingUrl: 'http://tracking.example.com/CONT567890',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal B',
            appointmentBookDate: '2025-01-30',
            truckerDetail: 'ABC Trucking',
            lfd: '2025-02-02',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2025-01-30',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU014', description: 'Product N', variation: 'Teal', unitCost: 98, orderQty: 230, weight: 1150, volume: 5.75, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2024-053',
            factory: 'Factory 7',
            warehouse: 'ARMS',
            createdDate: '2024-10-28',
            expectShipDate: '2024-12-28',
            eta: '2025-01-15',
            factoryAgent: 'Agent Martin',
            originPortName: 'Port 4',
            requestShipDate: '2024-12-28',
            poStatus: 'Arrived At WH',
            oceanFreight: 3750,
            drayage: 1000,
            chassis: 190,
            customDuties: 1200,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-11-20',
            readyDate: '2024-12-22',
            containerBookedDate: '2024-12-24',
            spaceReleasedDate: '2024-12-26',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-12-28',
            containerNumber: 'CONT678901',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: 'HBL678901',
            mbl: 'MBL678901',
            forwarder: 'DeWell',
            carrier: 'CMA CGM Securities B.V.',
            costBasis: 'CIF',
            vessel: 'Euro Carrier',
            freightRate: '3700',
            portDate: '2025-01-15',
            trackingUrl: 'http://tracking.example.com/CONT678901',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal C',
            appointmentBookDate: '2025-01-20',
            truckerDetail: 'XYZ Transport',
            lfd: '2025-01-25',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2025-01-20',
            warehouseDeliveryDate: '2025-01-21',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU015', description: 'Product O', variation: 'Navy', unitCost: 102, orderQty: 270, weight: 1350, volume: 6.75, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2024-054',
            factory: 'Factory 8',
            warehouse: 'FCI',
            createdDate: '2024-10-20',
            expectShipDate: '2024-12-20',
            eta: '2025-01-08',
            factoryAgent: 'Agent Thompson',
            originPortName: 'Port 1',
            requestShipDate: '2024-12-20',
            poStatus: 'Empty Notification',
            oceanFreight: 3280,
            drayage: 905,
            chassis: 168,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-11-12',
            readyDate: '2024-12-15',
            containerBookedDate: '2024-12-17',
            spaceReleasedDate: '2024-12-18',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-12-20',
            containerNumber: 'CONT789012',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL789012',
            mbl: 'MBL789012',
            forwarder: 'Donglixin',
            carrier: 'ZIM',
            costBasis: 'FOB',
            vessel: 'Asia Link',
            freightRate: '3250',
            portDate: '2025-01-08',
            trackingUrl: 'http://tracking.example.com/CONT789012',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal D',
            appointmentBookDate: '2025-01-12',
            truckerDetail: 'Fast Freight',
            lfd: '2025-01-18',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2025-01-12',
            warehouseDeliveryDate: '2025-01-13',
            emptyNotificationDate: '2025-01-14',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU016', description: 'Product P', variation: 'Maroon', unitCost: 87, orderQty: 200, weight: 1000, volume: 5, receivedQty: 0, damagedQty: 0, missingQty: 0 },
            { sku: 'SKU015', description: 'Product O', variation: 'Navy', unitCost: 102, orderQty: 270, weight: 1350, volume: 6.75, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },

        // INVENTORY EVENT POs (Empty Return, Inventoried)
        {
            poNumber: 'PO-2024-040',
            factory: 'Factory 1',
            warehouse: 'FCI',
            createdDate: '2024-10-10',
            expectShipDate: '2024-12-10',
            eta: '2024-12-28',
            factoryAgent: 'Agent Garcia',
            originPortName: 'Port 2',
            requestShipDate: '2024-12-10',
            poStatus: 'Empty Return',
            oceanFreight: 3180,
            drayage: 895,
            chassis: 162,
            customDuties: 1050,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-11-01',
            readyDate: '2024-12-05',
            containerBookedDate: '2024-12-07',
            spaceReleasedDate: '2024-12-08',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-12-10',
            containerNumber: 'CONT890123',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL890123',
            mbl: 'MBL890123',
            forwarder: 'Top Ocean',
            carrier: 'WHL',
            costBasis: 'CIF',
            vessel: 'Pacific Runner',
            freightRate: '3150',
            portDate: '2024-12-28',
            trackingUrl: 'http://tracking.example.com/CONT890123',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal E',
            appointmentBookDate: '2025-01-02',
            truckerDetail: 'Express Logistics',
            lfd: '2025-01-08',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2025-01-02',
            warehouseDeliveryDate: '2025-01-03',
            emptyNotificationDate: '2025-01-04',
            emptyPickupDate: '2025-01-05',
            emptyContainerReturnDate: '2025-01-06',
            items: [
                { sku: 'SKU017', description: 'Product Q', variation: 'Beige', unitCost: 93, orderQty: 245, weight: 1225, volume: 6.125, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2024-041',
            factory: 'Factory 2',
            warehouse: 'ARMS',
            createdDate: '2024-10-05',
            expectShipDate: '2024-12-05',
            eta: '2024-12-23',
            factoryAgent: 'Agent Martinez',
            originPortName: 'Port 3',
            requestShipDate: '2024-12-05',
            poStatus: 'Inventoried',
            oceanFreight: 3050,
            drayage: 875,
            chassis: 158,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-10-25',
            readyDate: '2024-11-30',
            containerBookedDate: '2024-12-02',
            spaceReleasedDate: '2024-12-03',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-12-05',
            containerNumber: 'CONT901234',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: 'HBL901234',
            mbl: 'MBL901234',
            forwarder: 'PNB',
            carrier: 'MSC',
            costBasis: 'FOB',
            vessel: 'Ocean Queen',
            freightRate: '3050',
            portDate: '2024-12-23',
            trackingUrl: 'http://tracking.example.com/CONT901234',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal F',
            appointmentBookDate: '2024-12-28',
            truckerDetail: 'Quick Ship',
            lfd: '2025-01-03',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2024-12-28',
            warehouseDeliveryDate: '2024-12-29',
            emptyNotificationDate: '2024-12-30',
            emptyPickupDate: '2024-12-31',
            emptyContainerReturnDate: '2025-01-02',
            items: [
                { sku: 'SKU018', description: 'Product R', variation: 'Mint', unitCost: 96, orderQty: 255, weight: 1275, volume: 6.375, receivedQty: 255, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2024-042',
            factory: 'Factory 3',
            warehouse: 'FCI',
            createdDate: '2024-09-28',
            expectShipDate: '2024-11-28',
            eta: '2024-12-16',
            factoryAgent: 'Agent Robinson',
            originPortName: 'Port 4',
            requestShipDate: '2024-11-28',
            poStatus: 'Inventoried',
            oceanFreight: 3380,
            drayage: 915,
            chassis: 172,
            customDuties: 1100,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-10-18',
            readyDate: '2024-11-22',
            containerBookedDate: '2024-11-24',
            spaceReleasedDate: '2024-11-26',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-11-28',
            containerNumber: 'CONT012345',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL012345',
            mbl: 'MBL012345',
            forwarder: 'FMED',
            carrier: 'Hapag-Lloyd',
            costBasis: 'CIF',
            vessel: 'Cargo Master',
            freightRate: '3350',
            portDate: '2024-12-16',
            trackingUrl: 'http://tracking.example.com/CONT012345',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal A',
            appointmentBookDate: '2024-12-20',
            truckerDetail: 'Prime Transport',
            lfd: '2024-12-26',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2024-12-20',
            warehouseDeliveryDate: '2024-12-21',
            emptyNotificationDate: '2024-12-22',
            emptyPickupDate: '2024-12-23',
            emptyContainerReturnDate: '2024-12-24',
            items: [
                { sku: 'SKU019', description: 'Product S', variation: 'Coral', unitCost: 89, orderQty: 225, weight: 1125, volume: 5.625, receivedQty: 225, damagedQty: 0, missingQty: 0 }
            ]
        },

        // Additional POs for better pagination testing
        {
            poNumber: 'PO-2024-043',
            factory: 'Factory 4',
            warehouse: 'ARMS',
            createdDate: '2024-09-20',
            expectShipDate: '2024-11-20',
            eta: '2024-12-08',
            factoryAgent: 'Agent Clark',
            originPortName: 'Port 1',
            requestShipDate: '2024-11-20',
            poStatus: 'Inventoried',
            oceanFreight: 3480,
            drayage: 935,
            chassis: 178,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-10-10',
            readyDate: '2024-11-15',
            containerBookedDate: '2024-11-17',
            spaceReleasedDate: '2024-11-18',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-11-20',
            containerNumber: 'CONT112233',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: 'HBL112233',
            mbl: 'MBL112233',
            forwarder: 'TOPOCEAN',
            carrier: 'Maersk',
            costBasis: 'FOB',
            vessel: 'Sea Navigator',
            freightRate: '3450',
            portDate: '2024-12-08',
            trackingUrl: 'http://tracking.example.com/CONT112233',
            telexRelease: 'Yes',
            customs: 'Yes',
            laceyAct: 'Yes',
            packingList: 'Yes',
            doField: 'Yes',
            vesselStatus: 'READY FOR APPOINTMENT',
            vesselStatusOther: '',
            terminal: 'Terminal B',
            appointmentBookDate: '2024-12-12',
            truckerDetail: 'Safe Delivery',
            lfd: '2024-12-18',
            penalty: '0',
            perDiemValue: '150',
            perDiemType: 'Calender',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '2024-12-12',
            warehouseDeliveryDate: '2024-12-13',
            emptyNotificationDate: '2024-12-14',
            emptyPickupDate: '2024-12-15',
            emptyContainerReturnDate: '2024-12-16',
            items: [
                { sku: 'SKU020', description: 'Product T', variation: 'Indigo', unitCost: 101, orderQty: 265, weight: 1325, volume: 6.625, receivedQty: 265, damagedQty: 0, missingQty: 0 }
            ]
        },
        {
            poNumber: 'PO-2025-012',
            factory: 'Factory 5',
            warehouse: 'FCI',
            createdDate: '2025-01-20',
            expectShipDate: '2025-03-25',
            eta: '2025-04-12',
            factoryAgent: 'Agent Lewis',
            originPortName: 'Port 2',
            requestShipDate: '2025-03-25',
            poStatus: 'Approved',
            oceanFreight: 2750,
            drayage: 860,
            chassis: 155,
            customDuties: 920,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: '',
            mbl: '',
            forwarder: '',
            carrier: '',
            costBasis: 'CIF',
            vessel: '',
            freightRate: '',
            portDate: '',
            trackingUrl: '',
            telexRelease: 'No',
            customs: '',
            laceyAct: '',
            packingList: '',
            doField: '',
            vesselStatus: '',
            vesselStatusOther: '',
            terminal: '',
            appointmentBookDate: '',
            truckerDetail: '',
            lfd: '',
            penalty: '',
            perDiemValue: '',
            perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '',
            warehouseDeliveryDate: '',
            emptyNotificationDate: '',
            emptyPickupDate: '',
            emptyContainerReturnDate: '',
            items: [
                { sku: 'SKU021', description: 'Product U', variation: 'Violet', unitCost: 84, orderQty: 195, weight: 975, volume: 4.875, receivedQty: 0, damagedQty: 0, missingQty: 0 }
            ]
        },

        // Additional POs for pagination testing (PO-2025-013 to PO-2025-030)
        {
            poNumber: 'PO-2025-013',
            factory: 'Factory 6',
            warehouse: 'ARMS',
            createdDate: '2025-01-22',
            expectShipDate: '2025-03-28',
            eta: '2025-04-15',
            factoryAgent: 'Agent Walker',
            originPortName: 'Port 3',
            requestShipDate: '2025-03-28',
            poStatus: 'Open',
            oceanFreight: 2650,
            drayage: 840,
            chassis: 152,
            customDuties: 0,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '', mbl: '', forwarder: '', carrier: '', costBasis: 'FOB', vessel: '', freightRate: '', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU022', description: 'Product V', variation: 'Cyan', unitCost: 77, orderQty: 160, weight: 800, volume: 4, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-014',
            factory: 'Factory 7',
            warehouse: 'FCI',
            createdDate: '2025-01-23',
            expectShipDate: '2025-03-30',
            eta: '2025-04-17',
            factoryAgent: 'Agent Young',
            originPortName: 'Port 4',
            requestShipDate: '2025-03-30',
            poStatus: 'Pending Approval',
            oceanFreight: 2900,
            drayage: 880,
            chassis: 162,
            customDuties: 1050,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: 'Budget approval needed',
            destinationPort: 'Louisville',
            hbl: '', mbl: '', forwarder: '', carrier: '', costBasis: 'CIF', vessel: '', freightRate: '', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU023', description: 'Product W', variation: 'Magenta', unitCost: 82, orderQty: 175, weight: 875, volume: 4.375, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-015',
            factory: 'Factory 8',
            warehouse: 'ARMS',
            createdDate: '2025-01-24',
            expectShipDate: '2025-04-01',
            eta: '2025-04-20',
            factoryAgent: 'Agent King',
            originPortName: 'Port 1',
            requestShipDate: '2025-04-01',
            poStatus: 'Approved',
            oceanFreight: 2550,
            drayage: 820,
            chassis: 148,
            customDuties: 0,
            factoryAgentApproval: 'No',
            expectedProductionStart: '',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '', mbl: '', forwarder: '', carrier: '', costBasis: 'FOB', vessel: '', freightRate: '', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU024', description: 'Product X', variation: 'Lime', unitCost: 91, orderQty: 220, weight: 1100, volume: 5.5, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-016',
            factory: 'Factory 1',
            warehouse: 'FCI',
            createdDate: '2025-01-25',
            expectShipDate: '2025-04-05',
            eta: '2025-04-25',
            factoryAgent: 'Agent Scott',
            originPortName: 'Port 2',
            requestShipDate: '2025-04-05',
            poStatus: 'Agent Approved',
            oceanFreight: 3100,
            drayage: 890,
            chassis: 165,
            customDuties: 980,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-02-28',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: '', mbl: '', forwarder: 'FMED', carrier: 'Hapag-Lloyd', costBasis: 'CIF', vessel: '', freightRate: '3050', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU025', description: 'Product Y', variation: 'Amber', unitCost: 86, orderQty: 205, weight: 1025, volume: 5.125, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-017',
            factory: 'Factory 2',
            warehouse: 'ARMS',
            createdDate: '2025-01-26',
            expectShipDate: '2025-04-10',
            eta: '2025-04-30',
            factoryAgent: 'Agent Green',
            originPortName: 'Port 3',
            requestShipDate: '2025-04-10',
            poStatus: 'In production',
            oceanFreight: 2980,
            drayage: 870,
            chassis: 160,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-03-01',
            readyDate: '',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '', mbl: '', forwarder: 'TOPOCEAN', carrier: 'Maersk', costBasis: 'FOB', vessel: '', freightRate: '2950', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU026', description: 'Product Z', variation: 'Crimson', unitCost: 94, orderQty: 235, weight: 1175, volume: 5.875, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-018',
            factory: 'Factory 3',
            warehouse: 'FCI',
            createdDate: '2025-01-27',
            expectShipDate: '2025-04-15',
            eta: '2025-05-05',
            factoryAgent: 'Agent Adams',
            originPortName: 'Port 4',
            requestShipDate: '2025-04-15',
            poStatus: 'Ready at Factory',
            oceanFreight: 3200,
            drayage: 910,
            chassis: 172,
            customDuties: 1080,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-03-05',
            readyDate: '2025-04-10',
            containerBookedDate: '',
            spaceReleasedDate: '',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '',
            containerNumber: '',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: '', mbl: '', forwarder: 'HLS', carrier: 'SLS', costBasis: 'CIF', vessel: '', freightRate: '3150', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU027', description: 'Product AA', variation: 'Slate', unitCost: 88, orderQty: 215, weight: 1075, volume: 5.375, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-019',
            factory: 'Factory 4',
            warehouse: 'ARMS',
            createdDate: '2025-01-28',
            expectShipDate: '2025-04-20',
            eta: '2025-05-10',
            factoryAgent: 'Agent Baker',
            originPortName: 'Port 1',
            requestShipDate: '2025-04-20',
            poStatus: 'Shipped',
            oceanFreight: 3300,
            drayage: 940,
            chassis: 175,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-03-10',
            readyDate: '2025-04-15',
            containerBookedDate: '2025-04-17',
            spaceReleasedDate: '2025-04-18',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-04-17',
            containerNumber: 'CONT334455',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: '', mbl: '', forwarder: 'DeWell', carrier: 'CMA CGM Securities B.V.', costBasis: 'FOB', vessel: '', freightRate: '3250', portDate: '', trackingUrl: '', telexRelease: 'No',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU028', description: 'Product AB', variation: 'Emerald', unitCost: 99, orderQty: 250, weight: 1250, volume: 6.25, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2025-020',
            factory: 'Factory 5',
            warehouse: 'FCI',
            createdDate: '2025-01-29',
            expectShipDate: '2025-04-25',
            eta: '2025-05-15',
            factoryAgent: 'Agent Carter',
            originPortName: 'Port 2',
            requestShipDate: '2025-04-25',
            poStatus: 'Shipped',
            oceanFreight: 2800,
            drayage: 850,
            chassis: 158,
            customDuties: 950,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2025-03-15',
            readyDate: '2025-04-20',
            containerBookedDate: '2025-04-22',
            spaceReleasedDate: '2025-04-24',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-04-24',
            containerNumber: 'CONT445566',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL445566', mbl: 'MBL445566', forwarder: 'Donglixin', carrier: 'ZIM', costBasis: 'CIF', vessel: 'Ocean Navigator', freightRate: '2750', portDate: '', trackingUrl: 'http://tracking.example.com/CONT445566', telexRelease: 'Yes',
            customs: '', laceyAct: '', packingList: '', doField: '', vesselStatus: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU029', description: 'Product AC', variation: 'Ruby', unitCost: 103, orderQty: 275, weight: 1375, volume: 6.875, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2024-055',
            factory: 'Factory 6',
            warehouse: 'ARMS',
            createdDate: '2024-11-01',
            expectShipDate: '2025-01-01',
            eta: '2025-01-20',
            factoryAgent: 'Agent Mitchell',
            originPortName: 'Port 3',
            requestShipDate: '2025-01-01',
            poStatus: 'Shipped',
            oceanFreight: 3380,
            drayage: 920,
            chassis: 168,
            customDuties: 0,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-11-25',
            readyDate: '2024-12-28',
            containerBookedDate: '2024-12-30',
            spaceReleasedDate: '2024-12-31',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2025-01-01',
            containerNumber: 'CONT556677',
            poModificationRequiredReason: '',
            destinationPort: 'LA/LB',
            hbl: 'HBL556677', mbl: 'MBL556677', forwarder: 'Top Ocean', carrier: 'WHL', costBasis: 'FOB', vessel: 'Sea Champion', freightRate: '3350', portDate: '', trackingUrl: 'http://tracking.example.com/CONT556677', telexRelease: 'Yes',
            customs: '', laceyAct: '', packingList: 'Yes', doField: '', vesselStatus: 'VESSEL', vesselStatusOther: '', terminal: '', appointmentBookDate: '', truckerDetail: '', lfd: '', penalty: '', perDiemValue: '', perDiemType: '',
            railOffDate: '',
            railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU030', description: 'Product AD', variation: 'Sapphire', unitCost: 107, orderQty: 290, weight: 1450, volume: 7.25, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        },
        {
            poNumber: 'PO-2024-056',
            factory: 'Factory 7',
            warehouse: 'FCI',
            createdDate: '2024-10-25',
            expectShipDate: '2024-12-25',
            eta: '2025-01-15',
            factoryAgent: 'Agent Perez',
            originPortName: 'Port 4',
            requestShipDate: '2024-12-25',
            poStatus: 'Arrived At Port',
            oceanFreight: 3500,
            drayage: 960,
            chassis: 182,
            customDuties: 1150,
            factoryAgentApproval: 'Factory Agent Approved',
            expectedProductionStart: '2024-11-18',
            readyDate: '2024-12-20',
            containerBookedDate: '2024-12-22',
            spaceReleasedDate: '2024-12-23',
            holdPO: 'No',
            holdReason: '',
            actualShipDate: '2024-12-25',
            containerNumber: 'CONT667788',
            poModificationRequiredReason: '',
            destinationPort: 'Louisville',
            hbl: 'HBL667788', mbl: 'MBL667788', forwarder: 'PNB', carrier: 'MSC', costBasis: 'CIF', vessel: 'Global Runner', freightRate: '3450', portDate: '2025-01-15', trackingUrl: 'http://tracking.example.com/CONT667788', telexRelease: 'Yes',
            customs: 'Yes', laceyAct: 'Yes', packingList: 'Yes', doField: 'Yes', vesselStatus: 'READY FOR APPOINTMENT', vesselStatusOther: '', terminal: 'Terminal C', appointmentBookDate: '', truckerDetail: '', lfd: '2025-01-25', penalty: '0', perDiemValue: '150', perDiemType: 'Calender',
            railOffDate: '', railOnDate: '',
            pickedDate: '', warehouseDeliveryDate: '', emptyNotificationDate: '', emptyPickupDate: '', emptyContainerReturnDate: '',
            items: [{ sku: 'SKU031', description: 'Product AE', variation: 'Topaz', unitCost: 97, orderQty: 240, weight: 1200, volume: 6, receivedQty: 0, damagedQty: 0, missingQty: 0 }]
        }
    ],

    // SKU Master Data
    skuMaster: [
        { sku: 'SKU001', description: 'Product A', variation: 'Blue', unitCost: 50, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8471.30.0100', availableStock: 250 },
        { sku: 'SKU002', description: 'Product B', variation: 'Red', unitCost: 75, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8471.30.0200', availableStock: 180 },
        { sku: 'SKU003', description: 'Product C', variation: 'Green', unitCost: 60, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9403.60.8080', availableStock: 320 },
        { sku: 'SKU004', description: 'Product D', variation: 'Black', unitCost: 90, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9403.60.8090', availableStock: 145 },
        { sku: 'SKU005', description: 'Product E', variation: 'White', unitCost: 85, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8528.52.0000', availableStock: 420 },
        { sku: 'SKU006', description: 'Product F', variation: 'Yellow', unitCost: 70, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6109.10.0012', availableStock: 580 },
        { sku: 'SKU007', description: 'Product G', variation: 'Orange', unitCost: 95, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6109.10.0027', availableStock: 290 },
        { sku: 'SKU008', description: 'Product H', variation: 'Purple', unitCost: 80, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8517.12.0050', availableStock: 175 },
        { sku: 'SKU009', description: 'Product I', variation: 'Gray', unitCost: 88, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9401.61.6011', availableStock: 95 },
        { sku: 'SKU010', description: 'Product J', variation: 'Brown', unitCost: 92, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9401.61.6021', availableStock: 210 },
        { sku: 'SKU011', description: 'Product K', variation: 'Pink', unitCost: 78, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6104.62.2010', availableStock: 450 },
        { sku: 'SKU012', description: 'Product L', variation: 'Silver', unitCost: 105, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8471.41.0150', availableStock: 85 },
        { sku: 'SKU013', description: 'Product M', variation: 'Gold', unitCost: 110, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8471.49.0000', availableStock: 120 },
        { sku: 'SKU014', description: 'Product N', variation: 'Teal', unitCost: 98, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9403.20.0050', availableStock: 165 },
        { sku: 'SKU015', description: 'Product O', variation: 'Navy', unitCost: 102, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6203.42.4011', availableStock: 335 },
        { sku: 'SKU016', description: 'Product P', variation: 'Maroon', unitCost: 87, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6203.42.4021', availableStock: 275 },
        { sku: 'SKU017', description: 'Product Q', variation: 'Beige', unitCost: 93, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9403.30.8000', availableStock: 190 },
        { sku: 'SKU018', description: 'Product R', variation: 'Mint', unitCost: 96, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8518.30.2000', availableStock: 225 },
        { sku: 'SKU019', description: 'Product S', variation: 'Coral', unitCost: 89, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6106.10.0010', availableStock: 510 },
        { sku: 'SKU020', description: 'Product T', variation: 'Indigo', unitCost: 101, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8519.81.4000', availableStock: 140 },
        { sku: 'SKU021', description: 'Product U', variation: 'Violet', unitCost: 84, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9401.71.0010', availableStock: 200 },
        { sku: 'SKU022', description: 'Product V', variation: 'Cyan', unitCost: 77, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8523.51.0000', availableStock: 310 },
        { sku: 'SKU023', description: 'Product W', variation: 'Magenta', unitCost: 82, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6110.20.2075', availableStock: 395 },
        { sku: 'SKU024', description: 'Product X', variation: 'Lime', unitCost: 91, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9403.40.9060', availableStock: 155 },
        { sku: 'SKU025', description: 'Product Y', variation: 'Amber', unitCost: 86, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8527.21.4040', availableStock: 260 },
        { sku: 'SKU026', description: 'Product Z', variation: 'Crimson', unitCost: 94, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6205.20.2065', availableStock: 340 },
        { sku: 'SKU027', description: 'Product AA', variation: 'Slate', unitCost: 88, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9403.89.6010', availableStock: 115 },
        { sku: 'SKU028', description: 'Product AB', variation: 'Emerald', unitCost: 99, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8536.69.8000', availableStock: 185 },
        { sku: 'SKU029', description: 'Product AC', variation: 'Ruby', unitCost: 103, weight: 5, volume: 0.025, category: 'Apparel', htsCode: '6204.62.4011', availableStock: 425 },
        { sku: 'SKU030', description: 'Product AD', variation: 'Sapphire', unitCost: 108, weight: 5, volume: 0.025, category: 'Electronics', htsCode: '8542.31.0001', availableStock: 75 },
        { sku: 'SKU031', description: 'Product AE', variation: 'Topaz', unitCost: 97, weight: 5, volume: 0.025, category: 'Furniture', htsCode: '9401.80.6010', availableStock: 130 }
    ],

    // Search SKUs by code or description (minimum 3 characters)
    searchSKUs(searchTerm) {
        if (!searchTerm || searchTerm.length < 3) {
            return [];
        }
        const term = searchTerm.toLowerCase();
        return this.skuMaster.filter(sku =>
            sku.sku.toLowerCase().includes(term) ||
            sku.description.toLowerCase().includes(term)
        ).slice(0, 10); // Limit to 10 results
    },

    // Get SKU by exact code
    getSKUByCode(skuCode) {
        return this.skuMaster.find(sku => sku.sku.toLowerCase() === skuCode.toLowerCase());
    },

    // Get all POs
    getAllPOs() {
        return this.purchaseOrders;
    },

    // Generate productName from items if not present
    getProductName(po) {
        if (po.productName) return po.productName;
        if (po.items && po.items.length > 0) {
            const item = po.items[0];
            if (item.description && item.variation) {
                return `${item.description} - ${item.variation}`;
            }
            return item.description || item.sku || '-';
        }
        return '-';
    },

    // Calculate total quantity from items
    getTotalQuantity(po) {
        if (po.totalQuantity) return po.totalQuantity;
        if (po.items && po.items.length > 0) {
            return po.items.reduce((sum, item) => sum + (item.orderQty || 0), 0);
        }
        return 0;
    },

    // Get POs filtered by role with computed fields
    getPOsByRole(role) {
        const filteredPOs = window.filterPOsByRole(this.purchaseOrders, role);
        // Add computed fields
        return filteredPOs.map(po => ({
            ...po,
            productName: this.getProductName(po),
            totalQuantity: this.getTotalQuantity(po)
        }));
    },

    // Get PO by number with computed fields
    getPOByNumber(poNumber) {
        const po = this.purchaseOrders.find(p => p.poNumber === poNumber);
        if (po) {
            return {
                ...po,
                productName: this.getProductName(po),
                totalQuantity: this.getTotalQuantity(po)
            };
        }
        return null;
    },

    // Update PO in the original data store
    updatePO(poNumber, updates) {
        const index = this.purchaseOrders.findIndex(p => p.poNumber === poNumber);
        if (index !== -1) {
            // Merge updates into the original PO object
            Object.assign(this.purchaseOrders[index], updates);
            return true;
        }
        return false;
    }
};

window.MockData = MockData;
